### PR TITLE
Update the Python/Django server to Django 2.1.7

### PR DESCRIPTION
**Pull request by SailingSteve**
Django 2.1.7 is 5 years ahead of the major version that we previously were using.
New install instructions for starting from scratch using PyCharm on Mac
A new manage.py command to create_dev_user for developers on localhost
Other misc fixes
Removed all hard tabs in the app, they were causing problems with the latest Django

Added a few days later:
Fixed the Django tests.
Having multiple DATABASES complicated things.
Fixed lots of tests that were broken due to updated "status" line changes
Added a page of instructions on how to work with Django tests.
(This additional commit contains all the changes from stevePythonFeb6b)

### CODE REVIEW

**Comment by SailingSteve** [comment]
```
(WeVoteServerPy3.7) Steves-MacBook-Pro-32GB-Oct-3171:WeVoteServer stevepodell$ ./manage.py test
Creating test database for alias 'default'...
Running
System check identified no issues (0 silenced).
..................................
----------------------------------------------------------------------
Ran 34 tests in 3.483s

OK
Destroying test database for alias 'default'...
(WeVoteServerPy3.7) Steves-MacBook-Pro-32GB-Oct-3171:WeVoteServer stevepodell$ 
```

**Comment by SailingSteve** [comment]
```
(WeVoteServerPy3.7) Steves-MacBook-Pro-32GB-Oct-3171:WeVoteServer stevepodell$ ./manage.py test
Creating test database for alias 'default'...
Running
System check identified no issues (0 silenced).
..................................
----------------------------------------------------------------------
Ran 34 tests in 6.687s

OK
Destroying test database for alias 'default'...
(WeVoteServerPy3.7) Steves-MacBook-Pro-32GB-Oct-3171:WeVoteServer stevepodell$ 
```

**Comment by SailingSteve** [comment]
Resolves WeVoteServer/pull/1004

**Comment by SailingSteve** [comment]
Resolves wevote/WeVoteServer/issues/1001

**Comment by DaleMcGrew** [comment]
Thank you Steve for this huge amount of work! I am putting this pull request through it's paces now in preparation for upgrading the live servers this coming Sunday. 👍

**Pull request merged**
